[tool.ruff]

select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "UP",  # pyupgrade,
    "I",   # isort
    "UP", # pyupgrade
    "ASYNC",
    "BLE", # Blind Exception
    "T20", # Found a print!
    "RET", # Unnecessary return
    "SIM", # Simplify
]
exclude = [
    "tests",
]

line-length = 120

[tool.black]

line-length = 120