on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up CPython
      uses: actions/setup-python@v4
    
    - name: Install dependencies
      id: install-deps
      run: |
          python -m pip install --upgrade pip setuptools wheel ruff 
    
    - name: Black format
      uses: psf/black@stable
    
    - name: Ruff Check
      run: ruff check .
  
    
 
